
services:

  app:
    build: ./app

    ports:
      - "8000:8000"

    depends_on:
      - db

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  db:
    image: postgres:16

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: